/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ACCESODATOS.ABMhabitacion;
import ACCESODATOS.Conexion;
import Entidades.Habitacion;
import Entidades.TipoDeHabitacion;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class HabitacionEstado extends javax.swing.JInternalFrame {
    DefaultTableModel modelo= new DefaultTableModel();
    private Connection con = null;

    /**
     * Creates new form HabitacionEstado
     */
    public HabitacionEstado() {
        con= Conexion.getConexion();
        initComponents();
        cargarCombo();
        cabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JCBtipoDeHabitacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDehabitacionesPorTipo = new javax.swing.JTable();
        JBnuevo = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("HABITACION");

        jLabel2.setText("TIPO DE HABITACION :");

        JCBtipoDeHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBtipoDeHabitacionActionPerformed(evt);
            }
        });

        tablaDehabitacionesPorTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDehabitacionesPorTipo);

        JBnuevo.setText("NUEVO");
        JBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCBtipoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(JBnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JCBtipoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(JBnuevo)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBtipoDeHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBtipoDeHabitacionActionPerformed
        // TODO add your handling code here:
        TipoDeHabitacion tiha= (TipoDeHabitacion)JCBtipoDeHabitacion.getSelectedItem();
        
        ABMhabitacion h= new ABMhabitacion();
        
        borraFila();
        
        for(Habitacion hab: h.gesttionHabitacion(tiha.getIdtipoDeHabitacion())){
            
            modelo.addRow(new Object[]{hab.getTipo(), hab.isEstado()+" desocupada"});
            
            
            
        }
        
    }//GEN-LAST:event_JCBtipoDeHabitacionActionPerformed

    private void JBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActionPerformed
        // TODO add your handling code here:
        borraFila();
    }//GEN-LAST:event_JBnuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBnuevo;
    private javax.swing.JComboBox<TipoDeHabitacion> JCBtipoDeHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDehabitacionesPorTipo;
    // End of variables declaration//GEN-END:variables

    public void cargarCombo(){
   JCBtipoDeHabitacion.addItem(new TipoDeHabitacion(0, 0, 0, " ", 0));
   JCBtipoDeHabitacion.addItem(new TipoDeHabitacion(2,400, 1, 1, "simple", 20000));
   JCBtipoDeHabitacion.addItem(new TipoDeHabitacion(3,500, 2, 2, "doble", 20000));
   JCBtipoDeHabitacion.addItem(new TipoDeHabitacion(4,600, 3, 3, "triple", 20000));
   JCBtipoDeHabitacion.addItem(new TipoDeHabitacion(7,1000, 2, 1, "suite lujo", 80000));
        
    }
    
    public void cabeceraTabla(){
        modelo.addColumn(" tipo de habitacion");
        modelo.addColumn("estado actual");
        tablaDehabitacionesPorTipo.setModel(modelo);
        
    }
    
    private void borraFila(){
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
    }


}
